# Generated by Django 2.1.1 on 2018-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181101_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
