# Generated by Django 2.1.1 on 2018-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181101_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_voted', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Speaker',
            new_name='Topic',
        ),
    ]
