# Generated by Django 2.1.1 on 2018-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181103_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='end_time',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='topics',
            name='start_time',
            field=models.CharField(max_length=40),
        ),
    ]
